version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "3000:80"
    volumes:
       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  
  test-app:
    build: .
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db
  
  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  mongo-db:
