version: '3'
services:
  nginx:
    ports:
      - "3000:80"
  test-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=3000
      - MONGO_USER=prashant
      - MONGO_PASSWORD=secret
      - SESSION_SECRET=secret
    command: npm run dev

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=prashant
      - MONGO_INITDB_ROOT_PASSWORD=secret